apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheuss-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /vol1/kpv/kube-prometheus
    server: 172.26.1.128
