apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  9090: "monitoring/monitoring-kube-prometheus-prometheus:9090"
  9093: "monitoring/monitoring-kube-prometheus-alertmanager:9093"
